default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: panmai
  password: mai0829341523

development:
  <<: *default
  database: yellowprint_dev

test:
  <<: *default
  database: yellowprint_test

production:
  <<: *default
  database: yellowprint_prod
